using System.Collections.Generic;

namespace Editor
{
    public static class BuildSettingsPresetsMenuItems
    {
        // Code in the below region is generated by BuildSettingsPresetsEditor, do NOT edit manually there

        #region Generated

        /// <summary>
        /// Guid => preset name
        /// </summary>
        public static Dictionary<string, string> presets = new Dictionary<string, string>()
        {
        };

        #endregion
    }
}