using System.Collections.Generic;
using UnityEditor;

namespace BuildSettingsPresets
{
    public static class BuildSettingsPresetsMenuItems
    {
        /// <summary>
        /// Guid => preset name
        /// </summary>
        public static readonly Dictionary<string, string> Presets = new Dictionary<string, string>()
        {
            // Code in the below region is generated by BuildSettingsPresetsEditor, do NOT edit manually there

            #region GeneratedPresets

			{"d42ad8b01c8a68846865607ee58cdd0e", "Default"},

            #endregion
        };

        // Code in the below region is generated by BuildSettingsPresetsEditor, do NOT edit manually there

        #region GeneratedMenuItems

		[MenuItem("Build presets/Default")]
		public static void Applyd42ad8b01c8a68846865607ee58cdd0e()
		{
			BuildSettingsPresetsManager.ApplyPreset("d42ad8b01c8a68846865607ee58cdd0e");
		}

        #endregion
    }
}
