namespace Editor
{
    public class BuildSettingsPresetsMenuItems
    {
        // Code in the below region is generated by BuildSettingsPresetsEditor, do NOT edit manually there
        #region Generated
        #endregion
    }
}
